USE OMOK; 

DROP TRIGGER IF EXISTS INSERT_USER;

DELIMITER ?!
CREATE TRIGGER INSERT_USER AFTER INSERT
ON USER
FOR EACH ROW
BEGIN
	DECLARE _S_U_NAME VARCHAR(10);
    SET _S_U_NAME = (SELECT NEW.U_NAME);
    INSERT INTO SCORE(S_POSITION, S_U_NAME) VALUES
		("BLACK", _S_U_NAME), ("WHITE", _S_U_NAME);
END ?!
DELIMITER ;

DROP TRIGGER IF EXISTS INSERT_RESULT;

DELIMITER ?!
CREATE TRIGGER INSERT_RESULT AFTER INSERT
ON RESULT
FOR EACH ROW
BEGIN
	DECLARE _RE_WINNER ENUM("BLACK", "WHITE", "DRAW");
    DECLARE _RO_B_U_NAME VARCHAR(10);
    DECLARE _RO_W_U_NAME VARCHAR(10);
    
    SET _RE_WINNER = (
		SELECT NEW.RE_WINNER);
    SET _RO_B_U_NAME = (
		SELECT RO_B_U_NAME
        FROM ROOM
        WHERE RO_ID = NEW.RE_RO_ID);
	SET _RO_W_U_NAME = (
		SELECT RO_W_U_NAME
        FROM ROOM
        WHERE RO_ID = NEW.RE_RO_ID);
        
	CALL INSERT_SCORE(_RE_WINNER, _RO_B_U_NAME, _RO_W_U_NAME);
END ?!
DELIMITER ;