USE OMOK; 

DROP TRIGGER IF EXISTS INSERT_USER;

DELIMITER ?!
CREATE TRIGGER INSERT_USER AFTER INSERT
ON USER
FOR EACH ROW
BEGIN
	DECLARE _S_U_NUM INT;
    SET _S_U_NUM = (SELECT NEW.U_NUM);
    INSERT INTO SCORE(S_POSITION, S_U_NUM) VALUES
		("BLACK", _S_U_NUM), ("WHITE", _S_U_NUM);
END ?!
DELIMITER ;

DROP TRIGGER IF EXISTS INSERT_RESULT;

DELIMITER ?!
CREATE TRIGGER INSERT_RESULT AFTER INSERT
ON RESULT
FOR EACH ROW
BEGIN
	DECLARE _S_U_NUM INT;
    DECLARE _S_POSITION ENUM("BLACK", "WHITE");
    DECLARE _R_OUTCOME ENUM("WIN", "LOSE", "DRAW");
    
    SET _S_U_NUM = (SELECT NEW.R_U_NUM);
	SET _S_POSITION = (SELECT NEW.R_POSITION);
    SET _R_OUTCOME = (SELECT NEW.R_OUTCOME);
    
    UPDATE SCORE
    SET S_COUNT = S_COUNT + 1,
		S_WIN = CASE _R_OUTCOME WHEN "WIN" THEN S_WIN + 1 ELSE S_WIN END,
        S_LOSE = CASE _R_OUTCOME WHEN "LOSE" THEN S_LOSE + 1 ELSE S_LOSE END,
        S_DRAW = CASE _R_OUTCOME WHEN "DRAW" THEN S_DRAW + 1 ELSE S_DRAW END
	WHERE 
		S_U_NUM = _S_U_NUM AND S_POSITION = _S_POSITION;
    
END ?!
DELIMITER ;



