USE OMOK; 

DROP PROCEDURE IF EXISTS GET_WIN_RATE;

DELIMITER ?!
CREATE PROCEDURE GET_WIN_RATE(
	IN _U_NUM INT,
    OUT _WIN_RATE DOUBLE,
    OUT _BLACK_WIN_RATE DOUBLE,
    OUT _WHITE_WIN_RATE DOUBLE
)
BEGIN 
	DECLARE _ALL_COUNT INT;
    DECLARE _WIN_COUNT INT;
    DECLARE _BLACK_COUNT INT;
    DECLARE _WHITE_COUNT INT;
    DECLARE _BLACK_WIN INT;
END ?!
DELIMITER ;

SELECT S_U_NUM, SUM(S_COUNT), SUM(S_WIN)
FROM SCORE
GROUP BY S_U_NUM;