USE OMOK; 

DROP PROCEDURE IF EXISTS INSERT_SCORE;

DELIMITER ?!
CREATE PROCEDURE INSERT_SCORE(
	IN _RE_WINNER ENUM("BLACK", "WHITE", "DRAW"),
    IN _RO_B_U_NAME VARCHAR(10),
    IN _RO_W_U_NAME VARCHAR(10)
)
BEGIN
	UPDATE SCORE
    SET S_COUNT = S_COUNT + 1,
		S_WIN = CASE _RE_WINNER WHEN "BLACK" THEN S_WIN + 1 ELSE S_WIN END,
        S_LOSE = CASE _RE_WINNER WHEN "WHITE" THEN S_LOSE + 1 ELSE S_LOSE END,
        S_DRAW = CASE _RE_WINNER WHEN "DRAW" THEN S_DRAW + 1 ELSE S_DRAW END
	WHERE 
		S_U_NAME = _RO_B_U_NAME AND S_POSITION = "BLACK";
        
	UPDATE SCORE
    SET S_COUNT = S_COUNT + 1,
		S_WIN = CASE _RE_WINNER WHEN "WHITE" THEN S_WIN + 1 ELSE S_WIN END,
        S_LOSE = CASE _RE_WINNER WHEN "BLACK" THEN S_LOSE + 1 ELSE S_LOSE END,
        S_DRAW = CASE _RE_WINNER WHEN "DRAW" THEN S_DRAW + 1 ELSE S_DRAW END
	WHERE 
		S_U_NAME = _RO_W_U_NAME AND S_POSITION = "WHITE";
END ?!
DELIMITER ;
