DROP DATABASE IF EXISTS OMOK; 
CREATE DATABASE OMOK;

USE OMOK;

DROP TABLE IF EXISTS `RESULT`;

CREATE TABLE `RESULT` (
	`R_NUM`	INT PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`R_POSITION`	ENUM("BLACK", "WHITE") NOT	NULL,
	`R_OUTCOME`	ENUM("WIN", "LOSE", "DRAW") NOT	NULL,
	`R_DATE`	DATETIME DEFAULT CURRENT_TIMESTAMP NOT	NULL,
	`R_U_NUM`	INT	NOT NULL
);

DROP TABLE IF EXISTS `USER`;

CREATE TABLE `USER` (
	`U_NUM`	INT PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`U_NAME`	VARCHAR(10) NOT	NULL,
	`U_PW`	VARCHAR(20) NOT	NULL,
	`U_DEL`	ENUM("Y", "N") DEFAULT "N" NOT	NULL
);

DROP TABLE IF EXISTS `SCORE`;

CREATE TABLE `SCORE` (
	`S_NUM`	INT PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`S_POSITION`	ENUM("BLACK", "WHITE") NOT	NULL,
	`S_COUNT`	INT DEFAULT 0 NOT	NULL,
	`S_WIN`	INT DEFAULT 0 NOT	NULL,
	`S_LOSE`	INT DEFAULT 0 NOT	NULL,
	`S_DRAW`	INT DEFAULT 0 NOT	NULL,
	`S_U_NUM`	INT	NOT NULL
);

ALTER TABLE `RESULT` ADD CONSTRAINT `FK_USER_TO_RESULT_1` FOREIGN KEY (
	`R_U_NUM`
)
REFERENCES `USER` (
	`U_NUM`
);

ALTER TABLE `SCORE` ADD CONSTRAINT `FK_USER_TO_SCORE_1` FOREIGN KEY (
	`S_U_NUM`
)
REFERENCES `USER` (
	`U_NUM`
);

